/** Маршруты экранов виджета (20 основных + gallery overlay states). */
export type WidgetScreenId =
  | "splash"
  | "splash-slide-2"
  | "splash-slide-3"
  | "start-page"
  | "start-page-alt"
  | "user-menu"
  | "user-menu-v2"
  | "create-profile-empty"
  | "create-profile-filled"
  | "create-profile-errors"
  | "create-profile-scroll-params"
  | "upload-photo"
  | "upload-photo-invalid"
  | "info-modal"
  | "configuring-generation"
  | "generation-page"
  | "generation-page-p2"
  | "generation-page-p2-v2"
  | "generation-item-config"
  | "preloader-v1"
  | "preloader-v2"
  | "popup-warning"
  | "popup-warning-clear-item"
  | "popup-warning-replace-outfit"
  | "popup-warning-delete-pose"
  | "popup-warning-delete-item-content"
  | "popup-warning-delete-wardrobe"
  | "my-images"
  | "my-images-delete"
  | "my-wardrobe"
  | "my-wardrobe-set-pick"
  | "my-wardrobe-edit"
  | "add-from-store"
  | "add-from-store-filter"
  | "add-from-wardrobe"
  | "change-background"
  | "change-background-custom"
  | "animate-image"
  | "animate-image-custom-pose";

export type WidgetRoute = WidgetScreenId;
