import type { WidgetConfig, WidgetColors } from "./types";
import defaultLogoUrl from "@/assets/brand/default-logo.svg";
import splashSlide1 from "@/assets/splash/splash-slide-1.png";
import splashSlide2 from "@/assets/splash/splash-slide-2.png";
import splashSlide3 from "@/assets/splash/splash-slide-3.png";
import { defaultAnimatePoseTiles, defaultBackgroundTiles } from "./default-tiles";
import { defaultUploadExamples } from "./uploadExamples";

/**
 * Светлая палитра — повторяет текущий дизайн виджета (#343537/#f5f5f5).
 */
const lightColors: WidgetColors = {
  primary: "#343537",
  onPrimary: "#ffffff",
  surface: "#ffffff",
  surfaceMuted: "#f5f5f5",
  text: "#343537",
  textMuted: "#6d6f73",
  border: "#f6f6f6",
  btnBg: "#343537",
  btnBgDisabled: "#6d6f73",
  btnText: "#ffffff",
  error: "#e63946",
  cardHero: "#f5f5f5",
  success: "#22c55e",
};

/**
 * Тёмная палитра — инверсия для встраивания на тёмные сайты.
 */
const darkColors: WidgetColors = {
  primary: "#f5f5f5",
  onPrimary: "#1a1b1d",
  surface: "#1a1b1d",
  surfaceMuted: "#2a2b2d",
  text: "#f5f5f5",
  textMuted: "#9a9ca0",
  border: "#2a2b2d",
  btnBg: "#f5f5f5",
  btnBgDisabled: "#4a4b4d",
  btnText: "#1a1b1d",
  error: "#ff6b75",
  cardHero: "#2a2b2d",
  success: "#4ade80",
};

/**
 * Дефолтные изображения слайдера splash-экрана.
 * Тематика: мода/одежда (как референс №1 от пользователя).
 * Унесены в public-ом смысле URL-ы Unsplash, чтобы админка могла переопределить.
 */
/** Слайды hero-карточки splash — экспорт из Try-on widget. */
const defaultSplashImages = [splashSlide1, splashSlide2, splashSlide3];

export const defaultWidgetConfig: WidgetConfig = {
  themeMode: "light",
  locale: "ru",
  i18n: {
    ru: {
      splash: {
        title: "Виртуальная примерка",
        subtitle: "Посмотрите, как вещь сидит на вас, не выходя из дома",
        cta: "продолжить",
      },
      start: {
        title: "Вариант примерки",
        expressTitle: "экспресс",
        expressDesc:
          "Быстрая примерка на готовую модель, без необходимости настраивать профиль",
        proTitle: "профессиональный",
        proDesc:
          "Создайте аватар со своими параметрами и примеряйте одежду на себя в приложении",
        agreeData: "Согласие на обработку своих персональных данных",
        agreePolicy:
          "Согласие с политикой конфиденциальности, пользовательским соглашением",
        cta: "начать примерку",
        profile: "профиль",
        poweredBy: "Разработано ",
        poweredByCompany: "Компанией",
      },
      userMenu: {
        items: {
          profile: "профиль",
          tryons: "мои примерки",
          wardrobe: "гардероб",
          stylist: "стилист",
        },
        legal: {
          privacy: "Политика конфиденциальности",
          terms: "Пользовательское соглашение",
          dataConsent: "согласие на обработку персональных данных",
        },
      },
      createProfile: {
        title: "Создать профиль",
        genderLabel: "Пол",
        genderFemale: "женщина",
        genderMale: "мужчина",
        genderChild: "ребёнок",
        photoHintOwn:
          "Если вы хотите использовать свою внешность, выберите вкладку «Свои фото» и загрузите фотографии.",
        photoHintModel:
          "Если вы не хотите использовать свою внешность, выберите одну из предложенных моделей.",
        seeMoreModels: "смотреть ещё",
        photoModeOwn: "свои фото",
        photoModeModel: "использовать модель",
        lookTab: "Образ",
        addLook: "Добавить образ",
        deleteLook: "Удалить образ",
        photoSlots: {
          portrait: "портрет: анфас",
          fullHeight: "в полный рост",
          back: "со спины",
          profile: "в профиль",
        },
        photoRequired: "*",
        removeAdditionalPhotos: "Убрать дополнительные фото",
        paramsTitle: "Параметры фигуры",
        paramsTabBasic: "базовые",
        paramsTabExtended: "расширенные",
        paramsTabDetailed: "детальные",
        paramsBasicHint:
          "Если вы хотите получать рекомендации по размеру, заполните детальные параметры фигуры.",
        bodyTypeLabel: "телосложение",
        breastSizeLabel: "размер груди",
        ageLabel: "возраст (лет)",
        heightLabel: "рост",
        figureShapeLabel: "тип фигуры",
        hipsSizeLabel: "размер бёдер",
        hipsShapeLabel: "форма бёдер",
        bellyShapeLabel: "живот",
        neckLengthLabel: "длина шеи",
        clothingSizeLabel: "размер одежды",
        shoeSizeLabel: "размер обуви",
        chosenPrefix: "выбрано: ",
        bodyTypeNames: {
          veryThin: "очень худое",
          thin: "худое",
          average: "среднее",
          slightlyFull: "слегка полное",
          full: "полное",
        },
        breastSizeNames: {
          verySmall: "очень маленькая",
          small: "маленькая",
          average: "средняя",
          large: "большая",
          veryLarge: "очень большая",
        },
        figureShapeNames: {
          rectangle: "прямоугольник",
          circle: "круг",
          invertedTriangle: "перевёрнутый треугольник",
          hourglass: "песочные часы",
          triangle: "треугольник",
        },
        hipsSizeNames: {
          narrow: "очень узкие",
          slightlyNarrow: "узкие",
          average: "средние",
          slightlyWide: "широкие",
          wide: "очень широкие",
        },
        hipsShapeNames: {
          square: "квадрат",
          pear: "груша (А-образные)",
          invertedTriangle: "перевёрнутый треугольник",
          circle: "круг",
          invertedHeart: "перевёрнутое сердце",
        },
        bellyShapeNames: {
          flat: "плоский",
          small: "небольшой",
          average: "средний",
          large: "большой",
        },
        neckLengthNames: {
          veryShort: "очень короткая",
          short: "короткая",
          average: "средняя",
          long: "длинная",
        },
        fields: {
          age: "возраст (лет)",
          height: "рост (см)",
          chest: "грудь (см)",
          waist: "талия (см)",
          hips: "обхват бёдер (см)",
          shoulderSize: "размер плеч (см)",
          footLength: "длина стопы (см)",
          footWidth: "ширина в косточке (см)",
          footArch: "ширина в подъёме (см)",
        },
        legLengthLabel: "длина ног",
        shoulderShapeLabel: "форма плеч",
        shoulderShapeChosen: "выбраны: ",
        shoulderShapeNames: {
          normal: "нормальные",
          sloped: "низкие (покатые)",
          rectangular: "высокие (прямоугольные)",
          muscular: "мускулистые",
          bony: "костлявые (острые)",
        },
        howToMeasure: "как определить размер",
        sizeChart: "таблица размеров",
        addExtraParams: "указать дополнительные параметры",
        deleteProfile: "удалить профиль",
        cta: "Сохранить и продолжить",
        errorPhotos:
          "для создания профиля с вашей фотографией нужно загрузить обязательные снимки.",
        errorModel: "выберите модель для профиля.",
        errorRequired:
          "для создания профиля вам необходимо заполнить все обязательные поля",
        uploadDialog: {
          portraitTitle: "Загрузить фото анфас",
          fullHeightTitle: "Загрузить фото в полный рост",
          backTitle: "Загрузить фото со спины",
          profileTitle: "Загрузить фото в профиль",
          subtitle:
            "Снимите фото анфас прямо сейчас или выберите другой снимок из имеющихся.",
          showTips: "Смотреть рекомендации",
          hideTips: "Скрыть рекомендации",
          cameraBtn: "Камера",
          selectBtn: "Выбрать",
          tips: [
            "Лицо полностью открыто. Уберите солнцезащитные очки, маски и любые аксессуары, закрывающие черты лица.",
            "Откройте лоб и глаза. Волосы не должны свисать на лицо — обязательно уберите их со лба и от глаз.",
            "Руки не в кадре. Снимите себя так, чтобы руки не касались лица и не попадали в зону портрета.",
            "Нейтральное выражение. Постарайтесь расслабить лицо и смотреть прямо в камеру (как на паспорт), избегайте сильных улыбок или гримас.",
            "Равномерный свет. Используйте мягкое освещение спереди, чтобы на лице не было глубоких теней (особенно под носом и глазами).",
          ],
          tipsBySlot: {
            fullHeight: [
              "Покажите фигуру полностью. Кадр должен включать всё тело — от макушки до стоп. Не обрезайте части тела границами кадра.",
              "Одежда по фигуре. Избегайте слишком свободной или оверсайз одежды. Для объективной оценки фигуры выбирайте вещи, которые не скрывают её силуэт.",
              "Простая поза и прямой ракурс. Стойте ровно, не используйте сложных поз. Фотографируйтесь строго спереди, без сильных поворотов корпуса.",
              "Правильное селфи. Если снимаете себя сами, держите телефон на уровне живота — это помогает избежать искажений пропорций тела.",
              "Только вы в кадре. На фото должен быть один человек. Убедитесь, что в кадр не попали посторонние люди или отражения.",
            ],
          },
        },
        deleteProfileDialog: {
          title: "Вы действительно хотите удалить профиль?",
          confirm: "да, удалить",
          cancel: "отмена",
        },
        measureGuides: {
          height: {
            title: "Как измерить рост",
            steps: [
              { text: "Встаньте прямо у стены, пятки и лопатки прижаты к поверхности." },
              { text: "Измерьте расстояние от пола до макушки." },
            ],
          },
          chest: {
            title: "Как измерить грудь",
            steps: [
              { text: "Измеряйте по самой выступающей точке груди, лента параллельна полу." },
            ],
          },
          waist: {
            title: "Как измерить талию",
            steps: [
              { text: "Измеряйте в самом узком месте туловища, не втягивая живот." },
            ],
          },
          hips: {
            title: "Как измерить бёдра",
            steps: [
              { text: "Измеряйте по самой широкой части бёдер и ягодиц." },
            ],
          },
          shoulderSize: {
            title: "Как измерить плечи",
            steps: [
              { text: "Измерьте расстояние между крайними точками плечевых суставов." },
            ],
          },
          footLength: {
            title: "Как измерить длину стопы",
            steps: [
              { text: "Поставьте стопу на лист, отметьте крайние точки и измерьте расстояние." },
            ],
          },
          footWidth: {
            title: "Как измерить ширину стопы",
            steps: [
              { text: "Измерьте ширину в самой широкой части стопы." },
            ],
          },
          footArch: {
            title: "Как измерить подъём стопы",
            steps: [
              { text: "Измерьте высоту подъёма в самой высокой точке свода." },
            ],
          },
        },
        legLengthSizeChart: {
          title: "Таблица размеров длины ног",
          howToMeasureLink: "как измерить",
          columns: { eu: "EU", gost: "ГОСТ", length: "Длина, см" },
          rows: [
            { eu: "28", gost: "44", length: "71" },
            { eu: "30", gost: "46", length: "76" },
            { eu: "32", gost: "48", length: "81" },
            { eu: "34", gost: "50", length: "86" },
            { eu: "36", gost: "52", length: "91" },
          ],
        },
      },
      screens: {
        common: {
          search: "поиск",
          cancel: "отмена",
          save: "сохранить",
          apply: "применить",
          close: "закрыть",
          ok: "понятно",
          linkCopied: "ссылка скопирована",
          good: "хорошо",
          bad: "плохо",
          examples: "примеры",
          tips: "советы",
          secShort: "сек",
        },
        wardrobe: {
          addItem: "добавить вещь",
          addFromStore: "добавить из магазина",
          addSet: "добавить набор",
          selectSet: "выбрать",
          cancelPick: "отменить",
        },
        wardrobeSetAdd: {
          title: "добавить набор",
          typeValue: "набор раскладка (сет)",
          typeHint:
            "набор раскладка: выберите готовый сет, и сервис самостоятельно определит область применения.",
        },
        myImages: {
          title: "мои примерки",
          newTryOn: "новая примерка",
          deleteAria: "удалить примерку",
        },
        wardrobeEdit: {
          title: "редактировать",
          nameLabel: "название",
          uploadPhoto: "загрузить фото",
          photoTips: "как выбрать фото?",
          uploadExtra: "загрузить дополнительное фото",
          deleteItem: "удалить вещь",
        },
        store: {
          title: "добавить из магазина",
          pickTitle: "выбрать вещь",
          applicationAreaPrefix: "область применения",
          select: "выбрать",
          cancel: "отменить",
          addToWardrobe: "добавить в гардероб",
          tabStore: "магазин",
          tabWardrobe: "гардероб",
          emptySearch: "к сожалению, поиск не дал результатов.",
        },
        storeFilter: {
          title: "фильтр",
          apply: "применить",
          categories: {
            all: "все",
            tops: "верх",
            bottoms: "низ",
            footwear: "обувь",
            accessories: "аксессуары",
          },
        },
        catalogFilters: {
          title: "фильтры",
          back: "назад",
          resetAll: "сбросить всё",
          resetSection: "сбросить",
          show: "показать",
          cancel: "отмена",
          removeChip: "убрать фильтр",
          chipType: "тип",
          chipColor: "цвет",
          chipComposition: "состав",
          chipPrice: "цена",
          sections: {
            color: "цвет",
            composition: "состав",
            category: "категория",
            price: "цена (₽)",
            length: "длина",
            style: "стиль",
            season: "сезон",
            material: "материал",
            sleeve: "тип рукава",
            cut: "покрой",
            model: "модель",
          },
          colors: {
            black: "черный",
            white: "белый",
            blue: "синий",
            red: "красный",
            yellow: "желтый",
            orange: "оранжевый",
            beige: "бежевый",
            green: "зеленый",
            purple: "фиолетовый",
            gray: "серый",
            pink: "розовый",
            lightBlue: "голубой",
            brown: "коричневый",
          },
          compositions: {
            cotton: "хлопок",
            linen: "лен",
            leather: "натуральная кожа",
            viscose: "вискоза",
            fleece: "флис",
            wool: "шерсть",
            elastane: "эластан",
          },
          productTypes: {
            jacket: "куртка",
            coat: "пальто",
            sheepskinCoat: "дубленка",
            downJacket: "пуховик",
            cardigan: "кофта",
            sweater: "свитер",
            jumper: "джемпер",
            vest: "жилет",
            dress: "платье",
            sundress: "сарафан",
            tshirt: "футболка",
            tankTop: "майка",
            swimsuit: "купальник",
            bra: "бюстгальтер",
          },
          materials: {
            leather: "кожа",
            ecoLeather: "эко-кожа",
            dermontin: "дермонтин",
            textile: "текстиль",
            velvet: "велюр",
            suede: "замша",
            denim: "джинс",
          },
          lengths: {
            short: "короткая",
            medium: "средняя",
            long: "длинная",
            maxi: "макси",
          },
          styles: {
            casual: "кэжуал",
            classic: "классика",
            sport: "спорт",
            evening: "вечерний",
          },
          seasons: {
            spring: "весна",
            summer: "лето",
            autumn: "осень",
            winter: "зима",
          },
          sleeves: {
            short: "короткий",
            long: "длинный",
            threeQuarter: "¾",
            sleeveless: "без рукавов",
          },
          cuts: {
            slim: "облегающий",
            regular: "прямой",
            oversize: "оверсайз",
            fitted: "приталенный",
          },
          models: {
            basic: "базовая",
            fitted: "по фигуре",
            relaxed: "свободная",
          },
        },
        wardrobeAdd: {
          title: "добавить вещь",
          uploadHint: "загрузите фото вещи",
          takePhoto: "сделать фото",
          fromGallery: "выбрать из галереи",
        },
        addSheet: {
          namePlaceholder: "укажите название",
          uploadPhoto: "загрузить фото",
          photoTips: "как выбрать фото?",
          add: "добавить",
        },
        background: {
          title: "сменить фон (телепорт)",
          search: "найти фон",
          addCustom: "добавить свой фон",
        },
        animate: {
          title: "оживить образ",
          search: "найти анимацию",
          addCustom: "добавить свою позу",
        },
        generation: {
          tryOn: "примерить",
          outfitTitle: "состав образа",
          buyAll: "купить всё",
          sizeWarning:
            "Внимание! Размер может отличаться. Рекомендации рассчитываются из указанных в вашем профиле размеров и информации, предоставленной производителем.",
          changeBackground: "сменить фон",
          animate: "оживить",
          share: "поделиться",
          configureOutfit: "настроить образ",
          clearOutfit: "очистить образ",
          moreActions: "ещё",
          moreMenu: {
            title: "образ",
            fullScreen: "на весь экран",
            howItWorks: "как это работает",
            share: "поделиться",
            clearOutfit: "очистить образ",
            deleteOutfit: "удалить образ",
          },
          shareMenu: {
            title: "поделиться",
            download: "скачать образ",
            copyLink: "скопировать ссылку",
            shareVia: "поделиться через",
          },
          addWear: {
            outfitTitle: "добавить элемент образа",
            accessoryTitle: "добавить аксессуар",
            tabs: {
              head: "голова",
              torso: "торс",
              legs: "ноги",
              feet: "стопы",
              face: "лицо",
              ears: "уши",
              neck: "шея",
              hands: "руки",
              back: "спина",
            },
          },
          itemConfig: {
            configurePrefix: "настроить",
            resetAll: "сбросить все настройки",
            clearItem: "очистить элемент",
            noOptions: "Для этого элемента нет дополнительных настроек.",
            noSettings: "у этой вещи нет настроек",
            fields: {
              visorSide: "сторона козырька",
              style: "стиль",
              fastener: "застёжка",
              sleeve: "рукав",
              sleeveRoll: "рукав",
              collarHeight: "ворот",
              collarType: "ворот",
              styling: "стилизация",
              cuffRoll: "стилизация",
              fit: "посадка",
              carryHand: "рука",
              lacing: "шнуровка",
              tuckedInFootwear: "в обувь",
              glassesPlacement: "положение",
            },
            options: {
              oversize: "оверсайз",
              fitted: "по фигуре",
              sleeveStraight: "расправить",
              sleeveRolled: "закатать",
              sleevePushed: "засучить",
              collarRegular: "обычный",
              collarStanding: "стоячий",
              stylingRegular: "обычная",
              stylingCuffed: "подвернутые",
              fitHigh: "высокая",
              fitRegular: "обычная",
              fitLow: "спущенная",
              handLeft: "левая",
              handRight: "правая",
              laced: "зашнуровано",
              unlaced: "не зашнуровано",
              tuckedIn: "заправлено",
              notTuckedIn: "не заправлено",
              onEyes: "на глазах",
              onHead: "на голове",
              onClothing: "на одежде",
            },
            sliderLabels: {
              visorFront: "спереди",
              visorRight: "справа",
              visorBack: "сзади",
              visorLeft: "слева",
              unbuttoned: "расстёгнута",
              buttoned: "застёгнута",
              pct0: "0%",
              pct50: "50%",
              pct100: "100%",
            },
          },
        },
        preloader: {
          label: "примерка",
          devDone: "завершить (dev)",
        },
        configuring: {
          selectProfile: "выберите профиль",
          selectPose: "выберите вид (ракурс)",
          editProfile: "редактировать профиль",
        },
        warning: {
          title: "Вы действительно хотите очистить весь образ?",
          confirm: "да, хочу",
          cancel: "отмена",
        },
        warnings: {
          clearOutfit: {
            title: "Вы действительно хотите очистить весь образ?",
            confirm: "да, хочу",
            cancel: "отмена",
          },
          clearItem: {
            title: "Вы действительно хотите очистить элемент?",
            confirm: "да, хочу",
            cancel: "отмена",
          },
          deleteWardrobeItem: {
            title: "Вы действительно хотите удалить вещь из своего гардероба?",
            confirm: "да, удалить",
            cancel: "отмена",
          },
          replaceOutfitWithSet: {
            title: "При добавлении готового набора остальные элементы образа будут удалены. Продолжить?",
            confirm: "да, продолжить",
            cancel: "отмена",
          },
          deletePose: {
            title: "Вы действительно хотите удалить позу?",
            confirm: "да, удалить",
            cancel: "отмена",
          },
          deleteItemContent: {
            title: "Элемент образа будет удалён вместе с содержимым. Продолжить?",
            confirm: "да, удалить",
            cancel: "отмена",
          },
          deleteTryOn: {
            title: "Вы действительно хотите удалить примерку?",
            confirm: "да, удалить",
            cancel: "отмена",
          },
          deleteOutfit: {
            title: "Вы действительно хотите удалить образ?",
            confirm: "да, удалить",
            cancel: "отмена",
          },
        },
      },
    },
    en: {
      splash: {
        title: "Virtual fitting room",
        subtitle: "See how it fits you without leaving home",
        cta: "Start fitting",
      },
      start: {
        title: "Fitting mode",
        expressTitle: "express",
        expressDesc:
          "Quick try-on on a ready-made model, no profile setup needed",
        proTitle: "professional",
        proDesc:
          "Create an avatar with your measurements and try clothes on yourself",
        agreeData: "I agree to the processing of my personal data",
        agreePolicy: "I agree to the privacy policy and terms of service",
        cta: "start try-on",
        profile: "profile",
        poweredBy: "Powered by ",
        poweredByCompany: "Company",
      },
      userMenu: {
        items: {
          profile: "profile",
          tryons: "my try-ons",
          wardrobe: "wardrobe",
          stylist: "stylist",
        },
        legal: {
          privacy: "Privacy policy",
          terms: "Terms of service",
          dataConsent: "Personal data processing consent",
        },
      },
      createProfile: {
        title: "Create profile",
        genderLabel: "Gender",
        genderFemale: "women's",
        genderMale: "men's",
        genderChild: "child",
        photoHintOwn:
          "If you want to use your own appearance, select the \"Own photos\" tab and upload photos.",
        photoHintModel:
          "If you don't want to use your own appearance, choose one of the suggested models.",
        seeMoreModels: "see more",
        photoModeOwn: "own photos",
        photoModeModel: "use model",
        lookTab: "Look",
        addLook: "Add look",
        deleteLook: "Delete look",
        photoSlots: {
          portrait: "portrait: front",
          fullHeight: "full height",
          back: "back",
          profile: "profile",
        },
        photoRequired: "*",
        removeAdditionalPhotos: "Remove additional photos",
        paramsTitle: "Body parameters",
        paramsTabBasic: "basic",
        paramsTabExtended: "extended",
        paramsTabDetailed: "detailed",
        paramsBasicHint:
          "If you want size recommendations, fill in the detailed body parameters.",
        bodyTypeLabel: "body type",
        breastSizeLabel: "chest size",
        ageLabel: "age (years)",
        heightLabel: "height",
        figureShapeLabel: "body shape",
        hipsSizeLabel: "hips size",
        hipsShapeLabel: "hips shape",
        bellyShapeLabel: "belly",
        neckLengthLabel: "neck length",
        clothingSizeLabel: "clothing size",
        shoeSizeLabel: "shoe size",
        chosenPrefix: "selected: ",
        bodyTypeNames: {
          veryThin: "very thin",
          thin: "thin",
          average: "average",
          slightlyFull: "slightly full",
          full: "full",
        },
        breastSizeNames: {
          verySmall: "very small",
          small: "small",
          average: "average",
          large: "large",
          veryLarge: "very large",
        },
        figureShapeNames: {
          rectangle: "rectangle",
          circle: "circle",
          invertedTriangle: "inverted triangle",
          hourglass: "hourglass",
          triangle: "triangle",
        },
        hipsSizeNames: {
          narrow: "very narrow",
          slightlyNarrow: "narrow",
          average: "average",
          slightlyWide: "wide",
          wide: "very wide",
        },
        hipsShapeNames: {
          square: "square",
          pear: "pear (A-shaped)",
          invertedTriangle: "inverted triangle",
          circle: "round",
          invertedHeart: "inverted heart",
        },
        bellyShapeNames: {
          flat: "flat",
          small: "small",
          average: "average",
          large: "large",
        },
        neckLengthNames: {
          veryShort: "very short",
          short: "short",
          average: "average",
          long: "long",
        },
        fields: {
          age: "age (years)",
          height: "height (cm)",
          chest: "chest (cm)",
          waist: "waist (cm)",
          hips: "hips (cm)",
          shoulderSize: "shoulder size (cm)",
          footLength: "foot length (cm)",
          footWidth: "foot width (cm)",
          footArch: "foot arch width (cm)",
        },
        legLengthLabel: "leg length",
        shoulderShapeLabel: "shoulder shape",
        shoulderShapeChosen: "selected: ",
        shoulderShapeNames: {
          normal: "normal",
          sloped: "sloped",
          rectangular: "rectangular",
          muscular: "muscular",
          bony: "bony",
        },
        howToMeasure: "how to measure",
        sizeChart: "size chart",
        addExtraParams: "add extra parameters",
        deleteProfile: "delete profile",
        cta: "Save and continue",
        errorPhotos:
          "to create a profile with your photo, please upload the required images.",
        errorModel: "please select a model for your profile.",
        errorRequired:
          "to create a profile, please fill out all required fields",
        uploadDialog: {
          portraitTitle: "Upload front portrait",
          fullHeightTitle: "Upload full-height photo",
          backTitle: "Upload back photo",
          profileTitle: "Upload profile photo",
          subtitle:
            "Take a front-facing photo right now or pick an existing one.",
          showTips: "Show tips",
          hideTips: "Hide tips",
          cameraBtn: "Camera",
          selectBtn: "Select",
          tips: [
            "Face fully visible. Remove sunglasses, masks and any accessories covering facial features.",
            "Forehead and eyes uncovered. Hair should not fall on the face — push it away from forehead and eyes.",
            "Hands out of frame. Make sure your hands don't touch your face or appear in the portrait area.",
            "Neutral expression. Relax your face and look straight at the camera (passport-style); avoid strong smiles or grimaces.",
            "Even lighting. Use soft front lighting so your face has no deep shadows (especially under nose and eyes).",
          ],
          tipsBySlot: {
            fullHeight: [
              "Show your full figure. The frame must include your entire body — from the top of your head to your feet. Do not crop body parts at the frame edges.",
              "Fitted clothing. Avoid loose or oversized outfits. For an accurate body shape assessment, choose clothes that don't hide your silhouette.",
              "Simple pose, front-facing. Stand straight, avoid complex poses. Shoot strictly from the front, without strong body rotation.",
              "Proper selfie. If you take the photo yourself, hold the phone at waist level — this helps avoid body proportion distortion.",
              "Only you in frame. The photo must contain a single person. Make sure no other people or reflections appear in the frame.",
            ],
          },
        },
        deleteProfileDialog: {
          title: "Are you sure you want to delete this profile?",
          confirm: "yes, delete",
          cancel: "cancel",
        },
        measureGuides: {
          height: {
            title: "How to measure height",
            steps: [
              { text: "Stand straight against a wall with heels and shoulder blades touching the surface." },
              { text: "Measure the distance from the floor to the top of your head." },
            ],
          },
          chest: {
            title: "How to measure chest",
            steps: [
              { text: "Measure at the fullest part of the chest, keeping the tape parallel to the floor." },
            ],
          },
          waist: {
            title: "How to measure waist",
            steps: [
              { text: "Measure at the narrowest part of the torso without sucking in your stomach." },
            ],
          },
          hips: {
            title: "How to measure hips",
            steps: [
              { text: "Measure at the widest part of the hips and buttocks." },
            ],
          },
          shoulderSize: {
            title: "How to measure shoulders",
            steps: [
              { text: "Measure the distance between the outer edges of the shoulder joints." },
            ],
          },
          footLength: {
            title: "How to measure foot length",
            steps: [
              { text: "Place your foot on paper, mark the outer points and measure the distance." },
            ],
          },
          footWidth: {
            title: "How to measure foot width",
            steps: [
              { text: "Measure the width at the widest part of the foot." },
            ],
          },
          footArch: {
            title: "How to measure foot arch",
            steps: [
              { text: "Measure the arch height at the highest point of the instep." },
            ],
          },
        },
        legLengthSizeChart: {
          title: "Leg length size chart",
          howToMeasureLink: "how to measure",
          columns: { eu: "EU", gost: "GOST", length: "Length, cm" },
          rows: [
            { eu: "28", gost: "44", length: "71" },
            { eu: "30", gost: "46", length: "76" },
            { eu: "32", gost: "48", length: "81" },
            { eu: "34", gost: "50", length: "86" },
            { eu: "36", gost: "52", length: "91" },
          ],
        },
      },
      screens: {
        common: {
          search: "search",
          cancel: "cancel",
          save: "save",
          apply: "apply",
          close: "close",
          ok: "got it",
          linkCopied: "link copied",
          good: "good",
          bad: "bad",
          examples: "examples",
          tips: "tips",
          secShort: "sec",
        },
        wardrobe: {
          addItem: "add item",
          addFromStore: "add from store",
          addSet: "add set",
          selectSet: "select",
          cancelPick: "cancel",
        },
        wardrobeSetAdd: {
          title: "add set",
          typeValue: "set layout (set)",
          typeHint:
            "set layout: choose a ready-made set and the service will determine the application area.",
        },
        myImages: {
          title: "my try-ons",
          newTryOn: "new try-on",
          deleteAria: "delete try-on",
        },
        wardrobeEdit: {
          title: "edit",
          nameLabel: "name",
          uploadPhoto: "upload photo",
          photoTips: "how to choose a photo?",
          uploadExtra: "upload additional photo",
          deleteItem: "delete item",
        },
        store: {
          title: "add from store",
          pickTitle: "pick item",
          applicationAreaPrefix: "application area",
          select: "select",
          cancel: "cancel",
          addToWardrobe: "add to wardrobe",
          tabStore: "store",
          tabWardrobe: "wardrobe",
          emptySearch: "sorry, your search returned no results.",
        },
        storeFilter: {
          title: "filter",
          apply: "apply",
          categories: {
            all: "all",
            tops: "tops",
            bottoms: "bottoms",
            footwear: "footwear",
            accessories: "accessories",
          },
        },
        catalogFilters: {
          title: "filters",
          back: "back",
          resetAll: "reset all",
          resetSection: "reset",
          show: "show",
          cancel: "cancel",
          removeChip: "remove filter",
          chipType: "type",
          chipColor: "color",
          chipComposition: "composition",
          chipPrice: "price",
          sections: {
            color: "color",
            composition: "composition",
            category: "category",
            price: "price (₽)",
            length: "length",
            style: "style",
            season: "season",
            material: "material",
            sleeve: "sleeve type",
            cut: "cut",
            model: "model",
          },
          colors: {
            black: "black",
            white: "white",
            blue: "blue",
            red: "red",
            yellow: "yellow",
            orange: "orange",
            beige: "beige",
            green: "green",
            purple: "purple",
            gray: "gray",
            pink: "pink",
            lightBlue: "light blue",
            brown: "brown",
          },
          compositions: {
            cotton: "cotton",
            linen: "linen",
            leather: "genuine leather",
            viscose: "viscose",
            fleece: "fleece",
            wool: "wool",
            elastane: "elastane",
          },
          productTypes: {
            jacket: "jacket",
            coat: "coat",
            sheepskinCoat: "sheepskin coat",
            downJacket: "down jacket",
            cardigan: "cardigan",
            sweater: "sweater",
            jumper: "jumper",
            vest: "vest",
            dress: "dress",
            sundress: "sundress",
            tshirt: "t-shirt",
            tankTop: "tank top",
            swimsuit: "swimsuit",
            bra: "bra",
          },
          materials: {
            leather: "leather",
            ecoLeather: "eco leather",
            dermontin: "dermontin",
            textile: "textile",
            velvet: "velvet",
            suede: "suede",
            denim: "denim",
          },
          lengths: {
            short: "short",
            medium: "medium",
            long: "long",
            maxi: "maxi",
          },
          styles: {
            casual: "casual",
            classic: "classic",
            sport: "sport",
            evening: "evening",
          },
          seasons: {
            spring: "spring",
            summer: "summer",
            autumn: "autumn",
            winter: "winter",
          },
          sleeves: {
            short: "short",
            long: "long",
            threeQuarter: "¾",
            sleeveless: "sleeveless",
          },
          cuts: {
            slim: "slim",
            regular: "regular",
            oversize: "oversize",
            fitted: "fitted",
          },
          models: {
            basic: "basic",
            fitted: "fitted",
            relaxed: "relaxed",
          },
        },
        wardrobeAdd: {
          title: "add item",
          uploadHint: "upload item photo",
          takePhoto: "take photo",
          fromGallery: "choose from gallery",
        },
        addSheet: {
          namePlaceholder: "specify name",
          uploadPhoto: "upload photo",
          photoTips: "how to choose a photo?",
          add: "add",
        },
        background: {
          title: "change background (teleport)",
          search: "find background",
          addCustom: "add custom background",
        },
        animate: {
          title: "animate look",
          search: "find animation",
          addCustom: "add custom pose",
        },
        generation: {
          tryOn: "try on",
          outfitTitle: "outfit composition",
          buyAll: "buy all",
          sizeWarning:
            "Note: size may differ. Recommendations are based on your profile measurements and manufacturer information.",
          changeBackground: "change background",
          animate: "animate",
          share: "share",
          configureOutfit: "configure outfit",
          clearOutfit: "clear outfit",
          moreActions: "more",
          moreMenu: {
            title: "look",
            fullScreen: "full screen",
            howItWorks: "how it works",
            share: "share",
            clearOutfit: "clear look",
            deleteOutfit: "delete look",
          },
          shareMenu: {
            title: "share",
            download: "download look",
            copyLink: "copy link",
            shareVia: "share via",
          },
          addWear: {
            outfitTitle: "add outfit element",
            accessoryTitle: "add accessory",
            tabs: {
              head: "head",
              torso: "torso",
              legs: "legs",
              feet: "feet",
              face: "face",
              ears: "ears",
              neck: "neck",
              hands: "hands",
              back: "back",
            },
          },
          itemConfig: {
            configurePrefix: "configure",
            resetAll: "reset all settings",
            clearItem: "clear item",
            noOptions: "No additional settings for this item.",
            noSettings: "this item has no settings",
            fields: {
              visorSide: "visor side",
              style: "style",
              fastener: "fastening",
              sleeve: "sleeve",
              sleeveRoll: "sleeve",
              collarHeight: "collar",
              collarType: "collar",
              styling: "styling",
              cuffRoll: "styling",
              fit: "rise",
              carryHand: "hand",
              lacing: "lacing",
              tuckedInFootwear: "in footwear",
              glassesPlacement: "placement",
            },
            options: {
              oversize: "oversize",
              fitted: "fitted",
              sleeveStraight: "straight",
              sleeveRolled: "rolled",
              sleevePushed: "pushed up",
              collarRegular: "regular",
              collarStanding: "standing",
              stylingRegular: "regular",
              stylingCuffed: "cuffed",
              fitHigh: "high",
              fitRegular: "regular",
              fitLow: "low",
              handLeft: "left",
              handRight: "right",
              laced: "laced",
              unlaced: "unlaced",
              tuckedIn: "tucked in",
              notTuckedIn: "not tucked in",
              onEyes: "on eyes",
              onHead: "on head",
              onClothing: "on clothing",
            },
            sliderLabels: {
              visorFront: "front",
              visorRight: "right",
              visorBack: "back",
              visorLeft: "left",
              unbuttoned: "unbuttoned",
              buttoned: "buttoned",
              pct0: "0%",
              pct50: "50%",
              pct100: "100%",
            },
          },
        },
        preloader: {
          label: "try-on",
          devDone: "finish (dev)",
        },
        configuring: {
          selectProfile: "select profile",
          selectPose: "select view (angle)",
          editProfile: "edit profile",
        },
        warning: {
          title: "Are you sure you want to clear the entire outfit?",
          confirm: "yes, clear",
          cancel: "cancel",
        },
        warnings: {
          clearOutfit: {
            title: "Are you sure you want to clear the entire outfit?",
            confirm: "yes, clear",
            cancel: "cancel",
          },
          clearItem: {
            title: "Are you sure you want to clear this item?",
            confirm: "yes, clear",
            cancel: "cancel",
          },
          deleteWardrobeItem: {
            title: "Are you sure you want to remove this item from your wardrobe?",
            confirm: "yes, delete",
            cancel: "cancel",
          },
          replaceOutfitWithSet: {
            title: "Adding a ready-made set will remove other outfit items. Continue?",
            confirm: "yes, continue",
            cancel: "cancel",
          },
          deletePose: {
            title: "Are you sure you want to delete this pose?",
            confirm: "yes, delete",
            cancel: "cancel",
          },
          deleteItemContent: {
            title: "This outfit item will be removed along with its contents. Continue?",
            confirm: "yes, delete",
            cancel: "cancel",
          },
          deleteTryOn: {
            title: "Are you sure you want to delete this try-on?",
            confirm: "yes, delete",
            cancel: "cancel",
          },
          deleteOutfit: {
            title: "Are you sure you want to delete this look?",
            confirm: "yes, delete",
            cancel: "cancel",
          },
        },
      },
    },
  },
  theme: {
    light: lightColors,
    dark: darkColors,
    radius: {
      widget: "36px",
      card: "24px",
      button: "50px",
      tile: "12px",
    },
    shadow: {
      widget: "0 24px 64px -24px rgba(0,0,0,0.25)",
      card: "0 8px 24px -12px rgba(0,0,0,0.15)",
    },
    fonts: {
      heading: "'TikTok Sans', 'Manrope', sans-serif",
      body: "'Manrope', sans-serif",
    },
  },
  brand: {
    logoAlt: "TUMBASNCOD",
    siteUrl: undefined,
    logoUrl: defaultLogoUrl,
    logoAnimationEnabled: true,
    logoAnimation: "fadeIn",
    logoInvert: true,
  },
  splash: {
    enabled: true,
    images: defaultSplashImages,
    autoplayMs: 4000,
  },
  teleport: {
    backgrounds: defaultBackgroundTiles,
  },
  animateLook: {
    poses: defaultAnimatePoseTiles,
  },
  userMenu: {
    items: [
      { id: "profile", enabled: true, pinned: false },
      { id: "tryons", enabled: true, pinned: true },
      { id: "wardrobe", enabled: true, pinned: true },
      { id: "stylist", enabled: true, pinned: true },
    ],
    legal: {
      privacy: { enabled: true, href: undefined },
      terms: { enabled: true, href: undefined },
      dataConsent: { enabled: true, href: undefined },
    },
  },
  watermark: {
    enabled: true,
    text: "by Mall'ER",
    href: "https://tryon.mall-er.com/",
    openInNewTab: true,
    removableOnPlan: false,
  },
  createProfile: {
    genders: ["female", "male"],
    childToggleEnabled: true,
    photoModes: ["own", "model"],
    photoSlots: [
      { id: "portrait", enabled: true, required: true, fitMode: "cover" },
      {
        id: "fullHeight",
        enabled: true,
        required: true,
        fitMode: "cover",
      },
      { id: "back", enabled: true, required: false, fitMode: "cover" },
      { id: "profile", enabled: true, required: false, fitMode: "cover" },
    ],
    paramsTabs: ["basic", "extended", "detailed"],
    paramsFields: {
      basic: [
        { id: "age", min: 1, max: 99, step: 1, defaultValue: 30, unit: "лет" },
        { id: "height", min: 80, max: 220, step: 1, defaultValue: 165, unit: "см", hint: true },
        { id: "chest", min: 50, max: 160, step: 1, defaultValue: 90, unit: "см", hint: true },
        { id: "waist", min: 40, max: 160, step: 1, defaultValue: 60, unit: "см", hint: true },
        { id: "hips", min: 50, max: 160, step: 1, unit: "см", hint: true },
      ],
      extended: [
        { id: "shoulderSize", min: 30, max: 120, step: 1, defaultValue: 90, unit: "см", hint: true },
      ],
      detailed: [
        { id: "age", min: 1, max: 99, step: 1, defaultValue: 30, unit: "лет" },
        { id: "height", min: 80, max: 220, step: 1, defaultValue: 165, unit: "см", hint: true },
        { id: "chest", min: 50, max: 160, step: 1, defaultValue: 90, unit: "см", hint: true },
        { id: "waist", min: 40, max: 160, step: 1, defaultValue: 60, unit: "см", hint: true },
        { id: "hips", min: 50, max: 160, step: 1, unit: "см", hint: true },
      ],
    },
    legLengthOptions: ["28", "30", "32", "34", "36+"],
    clothingSizeOptions: ["XXS", "XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL"],
    shoeSizeOptions: [
      "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47",
    ],
    defaultClothingSize: "M",
    defaultShoeSize: "40",
    shoulderShapes: ["normal", "sloped", "rectangular", "muscular", "bony"],
    bodyTypes: ["veryThin", "thin", "average", "slightlyFull", "full"],
    breastSizes: ["verySmall", "small", "average", "large", "veryLarge"],
    figureShapes: ["rectangle", "circle", "invertedTriangle", "hourglass", "triangle"],
    hipsSizes: ["narrow", "slightlyNarrow", "average", "slightlyWide", "wide"],
    hipsShapes: ["square", "pear", "invertedTriangle", "circle", "invertedHeart"],
    bellyShapes: ["flat", "small", "average", "large"],
    neckLengths: ["veryShort", "short", "average", "long"],
    age: { min: 0, max: 99, step: 1, defaultValue: 30 },
    heightRanges: [
      { id: "140-146", label: "140–146" },
      { id: "147-153", label: "147–153" },
      { id: "154-160", label: "154–160" },
      { id: "161-167", label: "161–167" },
      { id: "168-174", label: "168–174" },
      { id: "175-181", label: "175–181" },
      { id: "182-188", label: "182–188" },
      { id: "189-195", label: "189–195" },
      { id: "196-202", label: "196–202" },
      { id: "203+", label: "203+" },
    ],
    defaultBodyType: "thin",
    defaultBreastSize: "small",
    defaultFigureShape: "hourglass",
    defaultHipsSize: "narrow",
    defaultHipsShape: "pear",
    defaultBellyShape: "flat",
    defaultNeckLength: "average",
    uploadExamples: defaultUploadExamples,
  },
};
