export { WidgetConfigProvider, useWidgetConfig, useWidgetCssVars } from "./WidgetConfigProvider";
export { defaultWidgetConfig } from "./defaults";
export { useWidgetOverrides } from "./overrides";
export type { WidgetOverrides } from "./overrides";
export type {
  WidgetConfig,
  WidgetTheme,
  WidgetColors,
  BrandConfig,
  LogoAnimationId,
  SplashConfig,
  ConfigTile,
  TeleportConfig,
  AnimateLookConfig,
  UserMenuConfig,
  UserMenuItemConfig,
  UserMenuItemId,
  LegalLinkConfig,
  WatermarkConfig,
  I18nDictionary,
  Locale,
  ThemeMode,
  DeepPartial,
  CreateProfileConfig,
  ProfilePhotoSlotConfig,
  ProfilePhotoSlotId,
  PhotoSlotFitMode,
  ProfileParamsTab,
  ProfileFieldId,
  ProfileFieldConfig,
  BodyTypeId,
  BreastSizeId,
  FigureShapeId,
  HipsSizeId,
  HipsShapeId,
  BellyShapeId,
  NeckLengthId,
  HeightRangeOption,
} from "./types";
